name: CI

on: [push, pull_request]

env:
  SLEEP_A_BIT: sleep 0.2
  VERBOSE: 1

jobs:
  whitespace-errors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      run: git diff-index --check --cached 4b825dc642cb6eb9a060e54bf8d69288fbee4904


  gcc9-x32-nostacktrace:
    runs-on: ubuntu-20.04
    env:
      CC: gcc
      STACKTRACE: no
      TARGET: x32
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

